### ISSUE TITLE
opencv version 

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [Po-Ting-lin/HairRemoval#1]
Hi lin, thanks for this nice repo.
i have some demand about body hair remove, could you tell more about your develop environment ?
thanks again.

**Comment by Po-Ting-lin** [comment]
Hi  feiwofeifeixiaowo,
What is the specific meaning of "develop environment"?

Lin

**Comment by feiwofeifeixiaowo** [comment]
hi lin, could you tell me which  opencv version did you use.
The development environment I am talking about refers to the version of the opencv and other libraries you used to develop this project.
sorry for late reply and bad english

**Comment by Po-Ting-lin** [comment]
Hi feiwofeifeixiaowo,

Sure!
In this repository, opencv 4.2.0 and Bulit-in C++ Standard Template Library are used.

Lin

**Comment by feiwofeifeixiaowo** [comment]
Thanks Lin.
